export const ROUTE_TITLE_MAP: Record<string, string> = {
  admin: "Admin",
  players: "Players",
  alliances: "Alliances",
  events: "Events",
  add: "Add Event",
  archived: "Archived",
  applications: "Applications",
  commanders: "Commanders",
  pairings: "Commanders Pairings",
  "skill-trees": "Commander Skill Trees",
  equipment: "Equipment",
  attributes: "Attributes",
  materials: "Materials",
  snapshots: "Snapshots",
  data: "Data",
  imports: "Imports",
  exports: "Exports",
  users: "Users",
  "verify-governor": "Verify & Link Governor",
  audit: "Audit Logs",
  settings: "Settings",
  integrations: "Integrations",
  system: "System",
  "upload-scan": "Upload Scan",
}

export const ROUTE_PAGE_META: Record<string, { title: string; description?: string }> = {
  admin: { title: "Admin Dashboard", description: "Administrative overview and tools." },
  governors: { title: "Governors", description: "Manage governor roster, stats, and links." },
  alliances: { title: "Alliances", description: "Manage alliances and snapshots." },
  events: { title: "Events", description: "Create, manage, and archive events." },
  applications: { title: "Applications", description: "Review and manage event applications." },
  commanders: { title: "Commanders", description: "Manage commanders catalog and metadata." },
  pairings: { title: "Commander Pairings", description: "Define and review primary/secondary pairings." },
  "skill-trees": { title: "Commander Skill Trees", description: "Manage commander skill tree references." },
  equipment: { title: "Equipment", description: "Manage equipment catalog and ownership." },
  attributes: { title: "Equipment Attributes", description: "Manage attributes and iconic attributes." },
  materials: { title: "Materials", description: "Manage materials and quantities for equipment." },
  snapshots: { title: "Snapshots", description: "View and compare player/alliance snapshots." },
  imports: { title: "Data Imports", description: "Upload and process kingdom data files." },
  exports: { title: "Data Exports", description: "Export filtered datasets to CSV/JSON." },
  users: { title: "Users", description: "Manage user accounts and roles." },
  "verify-governor": { title: "Verify & Link Governor", description: "Verify and link governor accounts to users." },
  audit: { title: "Audit Logs", description: "View system-wide user audit actions." },
  settings: { title: "Settings", description: "Configure kingdom settings and preferences." },
  integrations: { title: "Integrations", description: "Manage external integrations like Discord or webhooks." },
  system: { title: "System", description: "System health, migrations, and maintenance." },
  "upload-scan": { title: "Upload a Scan", description: "Upload a commander or scout report scan." },
}
